// Generated by CoffeeScript 1.10.0
(function() {
  var _receiveWebhook, moment, util;

  moment = require('moment-timezone');

  util = require('../util');

  _receiveWebhook = function(arg) {
    var body, info, message, payload, ref, text, title;
    body = arg.body;
    payload = body;
    if (!(payload.user_name === 'BugHD')) {
      return;
    }
    info = payload.datas[0];
    title = info.project_name + " " + info.project_version;
    text = "";
    if (info.issue_title) {
      text += "TITLE: " + info.issue_title + "\n";
    }
    if (info.issue_stack) {
      text += "STACK: " + info.issue_stack + "\n";
    }
    if (info.created_at) {
      text += "CREATED_AT: " + (moment(Number(info.created_at) * 1000).tz('Asia/Shanghai').format('YYYY-MM-DD hh:mm:ss'));
    }
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            title: title,
            text: text,
            redirectUrl: ((ref = info.uri) != null ? ref.length : void 0) ? info.uri : void 0
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = 'BugHD';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '实时收集应用崩溃信息，定位应用崩溃原因。',
      en: 'BugHD is a real-time crashes collection tool, it can find out the reasons of app crashes.'
    });
    this.description = util.i18n({
      zh: 'BugHD 可实时收集应用崩溃信息，帮你定位应用崩溃原因。可提供详尽的崩溃分析报告，快速地定位崩溃到代码行。',
      en: 'BugHD is a real-time crashes collection tool, it can find out the reasons of app crashes. It also provides detailed reports of crash analysis, which can help you find out the wrong lines of code quickly.'
    });
    this.iconUrl = util["static"]('images/icons/bughd@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到你的 BugHD 中使用。',
        en: 'Copy this web hook to your BugHD account to use it.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
