// Generated by CoffeeScript 1.10.0
(function() {
  var _receiveWebhook, util;

  util = require('../util');

  _receiveWebhook = function(arg) {
    var attachment, body, message, payload, ref;
    body = arg.body;
    payload = body != null ? body.payload : void 0;
    if (!payload) {
      return;
    }
    message = {};
    attachment = {
      category: 'quote',
      data: {}
    };
    if ((payload != null ? payload.outcome : void 0) === 'success') {
      attachment.data.title = "[" + payload.reponame + "] Build success: " + payload.subject;
    } else {
      attachment.data.title = "[" + payload.reponame + "] Build fail: " + payload.outcome;
      if (toString.call(payload.messages) === '[object Array]') {
        attachment.data.text = (ref = payload.messages) != null ? ref.map(function(message) {
          return (message != null ? message.message : void 0) || '';
        }).join('<br>') : void 0;
      }
    }
    attachment.data.redirectUrl = payload.build_url;
    message.attachments = [attachment];
    return message;
  };

  module.exports = function() {
    this.title = 'Circle CI';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '持续集成平台',
      en: 'Hosted Continuous Integration for web applications.'
    });
    this.description = util.i18n({
      zh: '持续集成平台',
      en: 'Hosted Continuous Integration for web applications. Set up your application for testing in one click, on the fastest testing platform on the internet.'
    });
    this.iconUrl = util["static"]('images/icons/circleci@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到 .circle.yml 中使用。',
        en: 'Copy this web hook to .circle.yml to use it.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
