// Generated by CoffeeScript 1.10.0
(function() {
  var util;

  util = require('../util');

  module.exports = function() {
    this.title = 'Email';
    this.isHidden = true;
    return this.iconUrl = util["static"]('images/icons/email@2x.png');
  };

}).call(this);
