// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, _addRSSUrl, rssUrl, util;

  _ = require('lodash');

  Promise = require('bluebird');

  util = require('../util');

  rssUrl = 'http://dev.gold.avosapps.com/jianliao/rss';

  _addRSSUrl = function(arg) {
    var integration;
    integration = arg.integration;
    integration.url = rssUrl;
    return integration;
  };

  module.exports = function() {
    var events, ref, service;
    service = this;
    this.title = '稀土掘金日报';
    this.template = 'form';
    this.group = 'rss';
    this.summary = util.i18n({
      zh: '挖掘最优质的互联网技术',
      en: 'Digging the best of Internet technology'
    });
    this.description = util.i18n({
      zh: '挖掘最优质的互联网技术',
      en: 'Digging the best of Internet technology'
    });
    this.iconUrl = util["static"]('images/icons/goldxitudaily@2x.png');
    if ((ref = process.env.NODE_ENV) === 'ga' || ref === 'prod') {
      this.serviceUrl = 'http://apps.teambition.corp:7411';
    } else {
      this.serviceUrl = 'http://localhost:7411';
    }
    this.registerEvent('before.integration.create', _addRSSUrl);
    events = ['integration.create', 'integration.remove', 'integration.update'];
    return events.forEach(function(event) {
      return service.registerEvent(event, function(req) {
        return service.httpPost(service.serviceUrl, {
          event: event,
          data: req.integration
        });
      });
    });
  };

}).call(this);
