// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, _receiveWebhook, util;

  _ = require('lodash');

  Promise = require('bluebird');

  util = require('../util');


  /**
   * Define handler when receive incoming webhook from heroku
   * @param  {Object}   req      Express request object
   * @param  {Object}   res      Express response object
   * @param  {Function} callback
   * @return {Promise}
   */

  _receiveWebhook = function(arg) {
    var body, message, payload;
    body = arg.body;
    payload = body;
    if (!payload) {
      return;
    }
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            redirectUrl: payload.url,
            text: payload.user + " deployed version " + payload.head + ",\ngit log: " + payload.git_log,
            title: "" + payload.app
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = 'Heroku';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '支持多种编程语言的云平台即服务。',
      en: 'A cloud platform as a service (PaaS).'
    });
    this.description = util.i18n({
      zh: 'Heroku 是支持多种编程语言的云平台即服务（PaaS）。接入后可以收到部署的通知。',
      en: 'Heroku is a cloud platform as a service (PaaS) supporting several programming languages.'
    });
    this.iconUrl = util["static"]('images/icons/heroku@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到你的 Heroku 中使用。',
        en: 'Copy this web hook to your Heroku account to use it.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
