// Generated by CoffeeScript 1.10.0
(function() {
  var _receiveWebhook, crypto, jkbUrl, util;

  crypto = require('crypto');

  util = require('../util');

  jkbUrl = 'https://qiye.jiankongbao.com';

  _receiveWebhook = function(arg) {
    var body, content, fault_time, integration, message, method, msg_id, payload, query, task_id, task_type, token;
    integration = arg.integration, method = arg.method, body = arg.body, query = arg.query;
    if (method === 'GET') {
      payload = query;
    } else {
      payload = body;
    }
    msg_id = payload.msg_id, task_id = payload.task_id, task_type = payload.task_type, fault_time = payload.fault_time, token = payload.token, content = payload.content;
    if (integration.token && crypto.createHash('md5').update("" + msg_id + task_id + fault_time + integration.token).digest('hex') !== token) {
      throw new Error("Invalid jiankongbao token " + token + ", msg_id: " + msg_id);
    }
    if (!(task_type && task_id)) {
      throw new Error('Invalid jiankongbao payload');
    }
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            text: decodeURIComponent(content || ''),
            redirectUrl: jkbUrl + "/task/" + task_type + "/" + task_id
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = '监控宝';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '端到端一体化云监控。',
      en: 'Jiankongbao is able to monitor website, servers, network, database, API, applications, performance, etc.'
    });
    this.description = util.i18n({
      zh: '监控宝能够实时监控网站、服务器、网络、数据库、API、应用程序、页面性能等。为话题添加监控宝聚合后，你就可以在简聊上收取相关的告警通知。',
      en: 'Jiankongbao is able to monitor website, servers, network, database, API, applications, performance, etc. Add after Jiankongbao aggregation for a topic, you can catch up on Talk received the warning notice.'
    });
    this.iconUrl = util["static"]('images/icons/jiankongbao@2x.png');
    this._fields.push({
      key: 'token',
      type: 'text',
      description: util.i18n({
        zh: '可选',
        en: 'Optional'
      })
    });
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到你的监控宝当中使用。你也可以在管理界面当中找到这个 web hook 地址。',
        en: 'Copy this web hook to your Jiankongbao to use it. You may also find this url in the manager tab.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
