// Generated by CoffeeScript 1.10.0
(function() {
  var _, _receiveWebhook, util;

  _ = require('lodash');

  util = require('../util');

  _receiveWebhook = function(arg) {
    var body, message, payload, text;
    body = arg.body;
    payload = body || {};
    switch (payload.event) {
      case 'delivered':
        text = 'Delivered messages';
        break;
      case 'dropped':
        text = "Dropped messages\nreason: " + payload.reason;
        break;
      case 'bounced':
        text = "Hard bounces\nerror: " + payload.error;
        break;
      case 'complained':
        text = "Spam complaints";
        break;
      case 'unsubscribed':
        text = "Unsubscribes\nuser-agent: " + payload['user-agent'];
        break;
      case 'clicked':
        text = "Clicks\nurl: " + payload['url'] + "\nuser-agent: " + payload['user-agent'];
        break;
      case 'opened':
        text = "Opens\nuser-agent: " + payload['user-agent'];
        break;
      default:
        return;
    }
    if (payload['message-headers']) {
      text += '\n\n' + JSON.parse(payload['message-headers']).map(function(header) {
        if (typeof header[1] === 'string') {
          return header[0] + ': ' + header[1];
        }
      }).filter(function(header) {
        return header;
      }).join('\n');
    }
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            text: text
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = 'Mailgun';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '邮件发送服务',
      en: 'Email service'
    });
    this.description = util.i18n({
      zh: '邮件发送服务',
      en: 'Email service'
    });
    this.iconUrl = util["static"]('images/icons/mailgun@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readOnly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到你的应用中来启用 Mailgun 聚合',
        en: 'To start using mailgun integration, copy this url to your application'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
