// Generated by CoffeeScript 1.10.0
(function() {
  var _, _receiveWebhook, util;

  _ = require('lodash');

  util = require('../util');

  _receiveWebhook = function(arg) {
    var body, integration, message, payload, text, title;
    integration = arg.integration, body = arg.body;
    payload = body;
    if (!payload.form) {
      return;
    }
    title = "MikeCRM: " + payload.form.name + " " + payload.form.title;
    text = [];
    _.forIn(payload.component, function(component) {
      if (component.title && component.value) {
        if (typeof component.value === 'object') {
          return text.push(component.title + " : " + (String(_.values(component.value))));
        } else {
          return text.push(component.title + " : " + component.value);
        }
      }
    });
    text = text.join('\n');
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            title: title,
            text: text,
            redirectUrl: payload.form.url
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = '麦客CRM';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '麦客CRM是一款轻量好用的表单和联系人管理工具。',
      en: 'MikeCRM is a light and useful tool for organizations or individuals to make, release and collect online-forms for all kind of reasons, mostly for marketing and customer management.'
    });
    this.description = util.i18n({
      zh: '麦客CRM是一款轻量好用的表单和联系人管理工具。以表单收集信息、以联系人管理信息、再以邮件和短信为营销出口，使企业能够更好地将信息传达给最终客户，从而帮助企业更轻松地达成客户管理和市场营销目标。',
      en: 'MikeCRM is a light and useful tool for organizations or individuals to make, release and collect online-forms for all kinds of reasons, mostly for marketing and customer management. MikeCRM collects form feedback, extracts valuable information about customers, and afterwards, trying to reach them by e-mail or short messages in due course. Through this "feedback and touch" way, MikeCRM is supposed to build a short and direct path connecting customers and their own customers.'
    });
    this.iconUrl = util["static"]('images/icons/mikecrm@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到你的麦客中使用。',
        en: 'Copy this web hook to your MikeCRM account to use it.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
