// Generated by CoffeeScript 1.10.0
(function() {
  var _, _receiveWebhook, util;

  _ = require('lodash');

  util = require('../util');

  _receiveWebhook = function(arg) {
    var authorName, body, content, imageUrl, message, payload, query, redirectUrl, text, title;
    query = arg.query, body = arg.body;
    payload = _.assign({}, query || {}, body || {});
    content = payload.content, authorName = payload.authorName, title = payload.title, text = payload.text, redirectUrl = payload.redirectUrl, imageUrl = payload.imageUrl;
    if (!((title != null ? title.length : void 0) || (text != null ? text.length : void 0) || (content != null ? content.length : void 0))) {
      throw new Error("Title and text can not be empty");
    }
    message = {
      body: content,
      authorName: authorName,
      attachments: [
        {
          category: 'quote',
          data: {
            title: title,
            text: text,
            redirectUrl: redirectUrl,
            imageUrl: imageUrl
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = 'SWATHub';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '简单、高效的云端自动化测试平台。',
      en: 'Simple and Efficient Test Automation on Cloud'
    });
    this.description = util.i18n({
      zh: '无需学习任何编程语言，SWATHub让你在云端快速创建和实施自动化测试。添加SWATHub聚合服务之后，你可以在简聊中收取自动化测试的状态信息和结果报告。',
      en: 'SWATHub enables building automated test scenarios on cloud in a code-less way. You can receive the test automation status messages, and execution reports in Talk.ai, by means of this SWATHub integration.'
    });
    this.iconUrl = util["static"]('images/icons/swathub@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readOnly: true,
      description: util.i18n({
        zh: 'Webhook url',
        en: 'Webhook url'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
