// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, _sendToHubot, _sendToRobot, qs, request, requestAsync, util;

  qs = require('querystring');

  Promise = require('bluebird');

  request = require('request');

  _ = require('lodash');

  requestAsync = Promise.promisify(request);

  util = require('../util');

  _sendToRobot = function(arg) {
    var message, ref, talkai;
    message = arg.message;
    talkai = this;
    if (!((ref = message.body) != null ? ref.length : void 0)) {
      return;
    }
    if (!(talkai.config.apikey && talkai.config.url)) {
      return;
    }
    return _sendToHubot.call(this, message);
  };

  _sendToHubot = function(message) {
    var talkai;
    talkai = this;
    return requestAsync({
      method: 'POST',
      url: talkai.config.url,
      body: message,
      json: true,
      timeout: 20000
    }).then(function(res) {
      if (!(res.statusCode >= 200 && res.statusCode < 300)) {
        throw new Error("Bad request " + res.statusCode);
      }
    });
  };

  module.exports = function() {
    this.title = '小艾';
    this.isHidden = true;
    this.iconUrl = util["static"]('images/icons/talkai@2x.png');
    this.config = util.config.talkai;
    return this.registerEvent('message.create', _sendToRobot);
  };

}).call(this);
