// Generated by CoffeeScript 1.10.0
(function() {
  var _receiveWebhook, util;

  util = require('../util');

  _receiveWebhook = function(arg) {
    var body, err, error, message, payload, ref, title;
    body = arg.body;
    payload = body != null ? body.payload : void 0;
    try {
      if (toString.call(payload) === '[object String]') {
        payload = JSON.parse(payload);
      }
      if (toString.call(payload) !== '[object Object]') {
        return false;
      }
    } catch (error) {
      err = error;
      return false;
    }
    if (!payload.status_message) {
      throw new Error('Params missing');
    }
    title = ("[" + payload.status_message + "] ") + (((ref = payload.repository) != null ? ref.name : void 0) + " #" + payload.number + " ") + ("(" + payload.branch + " - " + payload.commit.slice(0, 7) + ") by " + payload.author_name);
    message = {
      attachments: [
        {
          category: 'quote',
          data: {
            title: title,
            text: payload.message,
            redirectUrl: payload.build_url
          }
        }
      ]
    };
    return message;
  };

  module.exports = function() {
    this.title = 'Travis CI';
    this.template = 'webhook';
    this.summary = util.i18n({
      zh: '分布式持续集成服务',
      en: 'A distributed continuous integration @'
    });
    this.description = util.i18n({
      zh: 'Travis CI 是一个在线的，分布式的持续集成服务，用来构建及测试在 GitHub 托管的代码。',
      en: 'Travis CI is a distributed continuous integration @'
    });
    this.iconUrl = util["static"]('images/icons/travis@2x.png');
    this._fields.push({
      key: 'webhookUrl',
      type: 'text',
      readonly: true,
      description: util.i18n({
        zh: '复制 web hook 地址到 .travis.yml 中使用。',
        en: 'Copy this web hook to your .travis.yml to use it.'
      })
    });
    return this.registerEvent('service.webhook', _receiveWebhook);
  };

}).call(this);
